Script started on 2017年03月14日 (週二) 15時38分57秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m whoami;pwd
pd2vm
/home/pd2vm
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git congif -l
git: 'congif' is not a git command. See 'git --help'.

Did you mean this?
	config
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git config -l
user.name=boys9033
user.email=boys9033@gmail.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git clone http://github.com.[K/boys9033/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m 
Script done on 2017年03月14日 (週二) 15時40分48秒
